### ISSUE TITLE
(2) Generalize the eeris related historical calculations [2]

### ISSUE THREAD

**Issue by johnantonn** [AuthEceSoftEng/cenote-cockroach#16]
Currently, there is a eeris-related Lua script running in redis to calculate historical statistics. We need to make this more generic and application-agnostic. Maybe include a flag for these detailed calculations, project-wise.

**Comment by johnantonn** [comment]
From the one hand, every project needs to have a new property, named redisHist (Boolean), which will be true only in case the historical stats need to be calculated during write. But how is this value going to be visible to CockroachHandler.py? I see two options:
- Connect to mongo and read it from CockroachHandler
- Include the value in the payload (maybe only in case it's true)

Both options are expected to have a toll on performance, ideally only when the calculations need to take place (2nd option). What's your opinion? @iamnapo

**Comment by iamnapo** [comment]
I think a good approach would be saving this info in Mongodb, and have the server "inject" it to each event before sending it to kafka

**Comment by johnantonn** [comment]
> I think a good approach would be saving this info in Mongodb, and have the server "inject" it to each event before sending it to kafka

Yeah that's what I meant in the 2nd option.. It's some extra bytes in the payload sent to Kafka, but only in case the "flag's" value is TRUE.
